# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: AWS example workflow
on:
  push
env:
  AWS_REGION : "us-west-2"
# permission can be added at job level or workflow level    
permissions:
      id-token: write
      contents: read    # This is required for actions/checkout
jobs:
  SendEmailWithSES:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::270574063299:role/aws-test-github
          role-session-name: aws-test-github
          aws-region: ${{ env.AWS_REGION }}
      - name:  Send email
        run: |
          aws ses send-email --from aaron.brink@inrix.com --to ron.huang@inrix.com --subject "Test email" --text "Hello!"
